<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ChatGPTWebSdk\ChatGPTWebSdk.csproj" />
    <ProjectReference Include="..\ChatGPTWebSdk.Browser\ChatGPTWebSdk.Browser.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
