using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using YamlDotNet.RepresentationModel;

if (args.Length != 2)
{
    Console.Error.WriteLine("Usage: SpecGen <openapi.yaml> <repository-root>");
    return 1;
}
var bytes = File.ReadAllBytes(args[0]);
var yaml = new YamlStream();
// Only operation metadata and referenced parameters/bodies/responses are needed.
// Some upstream schema descriptions contain invalid literal-block indentation.
// Exclude schemas from the parsing projection; fingerprint the untouched source.
var source = Encoding.UTF8.GetString(bytes);
var projection = Regex.Replace(source, @"^  schemas:\r?\n.*?(?=^  [a-zA-Z]|\z)", "", RegexOptions.Multiline | RegexOptions.Singleline);
yaml.Load(new StringReader(projection));
var root = (YamlMappingNode)yaml.Documents[0].RootNode;
YamlNode? Find(YamlNode? node, string key) => node is YamlMappingNode map && map.Children.TryGetValue(new YamlScalarNode(key), out var value) ? value : null;
string Text(YamlNode? node) => node is YamlScalarNode scalar ? scalar.Value ?? "" : "";
string[] Keys(YamlNode? node) => node is YamlMappingNode map ? map.Children.Keys.Select(Text).ToArray() : [];
YamlNode Resolve(YamlNode node)
{
    var reference = Text(Find(node, "$ref"));
    if (!reference.StartsWith("#/")) return node;
    YamlNode value = root;
    foreach (var segment in reference[2..].Split('/')) value = Find(value, segment.Replace("~1", "/").Replace("~0", "~")) ?? throw new InvalidDataException(reference);
    return value;
}
string Literal(string value) => JsonSerializer.Serialize(value);
string Identifier(string value) => string.Concat(value.Split(['_', '-', '.'], StringSplitOptions.RemoveEmptyEntries).Select(s => char.ToUpperInvariant(s[0]) + s[1..]));
var operations = new List<object>();
var ids = new HashSet<string>();
var methodNames = new HashSet<string>();
var methods = new StringBuilder("// <auto-generated />\n#nullable enable\nnamespace ChatGPTWebSdk.OpenAI;\n\npublic sealed partial class OpenAiOperationsClient\n{\n");
foreach (var pathEntry in ((YamlMappingNode)Find(root, "paths")!).Children)
{
    var path = Text(pathEntry.Key);
    foreach (var methodEntry in ((YamlMappingNode)pathEntry.Value).Children)
    {
        var verb = Text(methodEntry.Key);
        if (verb is not ("get" or "post" or "put" or "patch" or "delete" or "head" or "options")) continue;
        var operation = methodEntry.Value;
        var id = Text(Find(operation, "operationId"));
        if (id.Length == 0) id = verb + Identifier(path.Replace("{", "").Replace("}", "").Replace("/", "_").Replace("?", "_").Replace("=", "_"));
        if (!ids.Add(id)) throw new InvalidDataException($"Duplicate operation: {id}");
        var parameters = new List<YamlNode>();
        foreach (var parameterSource in new[] { Find(pathEntry.Value, "parameters"), Find(operation, "parameters") })
            if (parameterSource is YamlSequenceNode sequence) parameters.AddRange(sequence.Children.Select(Resolve));
        string[] Required(string location) => parameters.Where(p => Text(Find(p, "in")) == location && Text(Find(p, "required")) == "true").Select(p => Text(Find(p, "name"))).Distinct().ToArray();
        var request = Find(operation, "requestBody");
        if (request is not null) request = Resolve(request);
        var responseTypes = new List<string>();
        if (Find(operation, "responses") is YamlMappingNode responses)
            foreach (var response in responses.Children.Where(r => Text(r.Key).StartsWith('2'))) responseTypes.AddRange(Keys(Find(Resolve(response.Value), "content")));
        operations.Add(new { id, method = verb.ToUpperInvariant(), path, summary = Text(Find(operation, "summary")),
            requiredPath = Required("path"), requiredQuery = Required("query"), requiredHeaders = Required("header"),
            requiresBody = Text(Find(request, "required")) == "true", requestMediaTypes = Keys(Find(request, "content")),
            responseMediaTypes = responseTypes.Distinct().ToArray(), deprecated = Text(Find(operation, "deprecated")) == "true" });
        var name = Identifier(id) + "Async";
        if (!methodNames.Add(name)) throw new InvalidDataException($"Duplicate C# method: {name}");
        methods.Append($"    public Task<ApiResult> {name}(ApiRequest? request = null, CancellationToken cancellationToken = default) =>\n        _client.SendAsync({Literal(id)}, request, cancellationToken);\n");
    }
}
methods.Append("}\n");
var output = Path.Combine(args[1], "src", "ChatGPTWebSdk", "Generated");
Directory.CreateDirectory(output);
var manifest = new { specSource = "https://raw.githubusercontent.com/openai/openai-openapi/refs/heads/main/openapi.yaml", specVersion = Text(Find(Find(root, "info"), "version")), sha256 = Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(), operations };
File.WriteAllText(Path.Combine(output, "openapi-operations.json"), JsonSerializer.Serialize(manifest, new JsonSerializerOptions { WriteIndented = true }) + "\n", new UTF8Encoding(false));
File.WriteAllText(Path.Combine(output, "OpenAiOperationsClient.g.cs"), methods.ToString(), new UTF8Encoding(false));
Console.WriteLine($"Generated {operations.Count} REST operations. SHA-256: {manifest.sha256}");
return 0;

