<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ChatGPTWebBundleDirectory Condition="'$(ChatGPTWebBundleDirectory)' == ''">$(MSBuildProjectDirectory)/..</ChatGPTWebBundleDirectory>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(ChatGPTWebBundleDirectory)/*.dll" />
    <Content Include="$(ChatGPTWebBundleDirectory)/.playwright/**/*" Link=".playwright/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <AssemblyMetadata Include="ChatGPTWebBundleDirectory" Value="$([System.IO.Path]::GetFullPath('$(ChatGPTWebBundleDirectory)'))" />
  </ItemGroup>
</Project>
